### ISSUE TITLE
Root bone issue 

### ISSUE THREAD

**Issue by whypeoplewhyy** [LunaCapra/CrewBoom#15]
The following message, was posted in the official modding section of the Reptile Hideout discord: Howdy hey everyone! After about an hour and a half of research and going over tutorials online, I am so close to getting King Dail from FP2 (thank you Vtuber Graphics from Fiverr) to be modded into this game. HOWEVER, I encountered an issue. Anybody willing to help me please, for the sake of the King Dail/Freedom Planet fandom? ^^ 

I rechecked all of the armature of this model and followed all the steps from the wiki. However, I still ran into this issue. Is this an issue with the model or the mod itself? I am not sure. Please update me when you can. 

https://github.com/LunaCapra/CrewBoom/assets/174835068/6d3bbe96-f789-4c4e-a73e-6bf0489a3d34

**Comment by LunaCapra** [comment]
If you need help with using the unity project, use the team reptile discord please.
This repository's issues are for bugs with the plugin only.
